### ISSUE TITLE
Any way to provide custom config to ClickHouse?

### ISSUE THREAD

**Issue by julienma** [dokku/dokku-clickhouse#2]
Hey team,
I'm adapting the [docker-compose](https://github.com/plausible/hosting/blob/master/docker-compose.yml) file from [Plausible](https://plausible.io/docs/self-hosting) to make it work on dokku.

I'm using this dokku-clickhouse plugin, and everything works fine.

However, in the docker-compose file, they're adding 2 custom `.xlm` configuration files for Clickhouse, via docker's volume feature:

```
  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
```

Do you have any idea on how I could provide those 2 config files to the clickhouse container?

---

Here's what I tried:

1. it seems the only [volume mounted by the plugin](https://github.com/dokku/dokku-clickhouse/blob/master/functions#L79) is `-v "$SERVICE_HOST_ROOT/data:/var/lib/clickhouse"` (also see [clickhouse dockerfile](https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/Dockerfile#L97)). I thought about copying the 2 custom `.xml` files in the `data` directory to make them available to the container, and then...
2. I thought I could use [`CLICKHOUSE_CUSTOM_ENV`](https://github.com/dokku/dokku-clickhouse/blob/96faa27d712b9c09e400988b51ebd42a8e5beb7c/functions#L60) to pass a config to clickhouse and tell it to load the custom configs from the `data` directory from step 1. But I can't find any ENV on clickhouse side that would let me pass a custom folder to load config from.

In fact it seems that clickhouse expects any custom configuration to be stored in 2 specific folders, `/etc/clickhouse-server/config.d/*.xml` and `/etc/clickhouse-server/usert.d/*.xml`, see https://github.com/ClickHouse/ClickHouse/tree/master/docker/server#volumes and https://clickhouse.tech/docs/en/operations/configuration-files/.

If there's no way currently to load / create on-the-fly a custom configuration, do you think it would be possible to add an option to this dokku plugin to mount 2 additional volumes for custom configuration files? E.g. add something along the lines of `-v "$SERVICE_HOST_ROOT/config/config.d/*.xml:/etc/clickhouse-server/config.d/*.xml" -v "$SERVICE_HOST_ROOT/config/users.d/*.xml:/etc/clickhouse-server/users.d/*.xml"`?

Thanks
